interface CheckStatusResult {
    result: number
    time: number
    flow: number
    fsele: number
    fee: number
    m46: number
    v46ip: string
    myv6ip: string
    oltime: number
    olflow: number
    lip: string
    stime: string
    etime: string
    uid: string
    v6af: number
    v6df: number
    v46m: number
    v4ip: string
    v6ip: string
    AC: string
    ss5: string
    ss6: string
    vid: number
    ss1: string
    ss4: string
    cvid: number
    pvid: number
    hotel: number
    aolno: number
    eport: number
    eclass: number
    zxopt: number
    NID: string
    olno: number
    udate: string
    olmac: string
    ollm: number
    olm1: string
    olm2: string
    olm3: number
    olmm: number
    olm5: number
    gid: number
    actM: number
    actt: number
    actdf: number
    actuf: number
    act6df: number
    act6uf: number
    allfm: number
    d1: number
    u1: number
    d2: number
    u2: number
    o1: number
    nd1: number
    nu1: number
    nd2: number
    nu2: number
    no1: number
}

interface LogoutResult {
    result: number
    wopt: number
    msg: number
    hidm: number
    hidn: number
    ss5: string
    ss6: string
    vid: number
    ss1: string
    ss4: string
    cvid: number
    pvid: number
    hotel: number
    aolno: number
    eport: number
    eclass: number
    time: number
    flow: number
    fsele: number
    fee: number
    v6af: number
    v6df: number
    emark: number
    actM: number
    actt: number
    actdf: number
    actuf: number
    act6df: number
    act6uf: number
    allfm: number
    d1: number
    u1: number
    d2: number
    u2: number
    o1: number
    nd1: number
    nu1: number
    nd2: number
    nu2: number
    no1: number
    uid: string
}

interface LoginResult {
    result: number
    aolno: number
    m46: number
    v46ip: string
    myv6ip: string
    sms: number
    ufee: number
    NID: string
    olno: number
    udate: string
    olmac: string
    ollm: number
    olm1: string
    olm2: string
    olm3: number
    olmm: number
    olm5: number
    gid: number
    olip: string
    oaf: number
    oat: number
    mac1: string
    mac2: string
    mac3: string
    mac4: string
    mac5: string
    mac6: string
    ac0: string
    oltime: number
    olflow: number
    lip: string
    stime: string
    etime: string
    uid: string
    sv: number
}
